### ISSUE TITLE
Joining the community

### ISSUE THREAD

**Issue by cassgvp** [cassgvp/WIN-Open-Neuroimaging-Community#2]
After having a quick look through the [Open WIN Community](https://cassgvp.github.io/WIN-Open-Neuroimaging-Community/) pages:

- [ ] Do you know how you would join the the community? 
- [ ] Do you know who you would contact if you wanted to find out more or had a question? 
- [ ] Would you feel comfortable asking a question or joining via one of the identified routes?
- [ ] Are there any other ways you would like to communicate with the community?

**Comment by lazaral** [comment]
It seems pretty clear to me how to join the community, and the Slack channel is a great idea! I'm probably biased though because I've been at WIN for a while and I like open science... I'd be curious to hear from other people - e.g. from people who joined WIN only recently, or who have not heard of open science before.

**Comment by cassgvp** [comment]
Comment from Verena Heise:

- already said that but Github is a barrier to me and I’m not a big fan of slack either. I think there are open source/ not-for-profit alternatives and I’d be keen to support those. As a very general comment, I’m keen to support open source alternatives whenever possible because that’s an important part of my definition of Open Science. It would be nice to educate the community about those issues, too, and is also part of my mission to promote “ethical” choices when it comes to the tools we use (or the journals we publish in for that matter)

**Comment by MalikaIhle** [comment]
> * [ ]  Do you know how you would join the the community?
YES
> * [ ]  Do you know who you would contact if you wanted to find out more or had a question?
YES
> * [ ]  Would you feel comfortable asking a question or joining via one of the identified routes?
Yes, your wording 'if you're not up for slack email me' is very inclusive
> * [ ]  Are there any other ways you would like to communicate with the community?
to address Verena's point: the current Free and Open Source group in Oxford also dislike Github and Slack as their are proprietary software (for instance, alternative could be a self hosted instance of gitlab instead of github, and a paid for or self hosted instance of rocket chat instead of slack). However, when referring to slack, one of the funding members of OxFOSS acknowledge that we need to give people what it wants to built and engage a community, and it is our job (OxFOSS - RROx - Open WIN) to convince them to switch to free (as in freedom) and open source alternative. Also, of course, and to a certain extent, the university policies and infrastructure also need to change and eventually support us and our communities with using open source tools.

**Comment by cassgvp** [comment]
I am currently working with IT to migrate this resource over to the WIN GitLab instance. There are some complications around the domain name created for "pages" sites, but there a re a few hacks to try. I'll share updates.

Re: Slack, yes... 😐. The big problem is who will support our own instance of rocket chat / Mattermost... I think this is a long term project around communication within WIN. If @MalikaIhle RROx were to set one up (or [URKN](https://www.ukrn.org)?), I'm sure we could join! Already getting feedback from others about "many different platforms" etc. so we will need to consider the added value as you describe with FOSS.

**Comment by jvohryzek** [comment]
It was very straightforward to join the mailing list as well as the slack channel:) plus the option to contact the administratorr directly is very inclusive.
Just to chip to the general discussion on the software used (although it has been mentioned) - I am also a fan of non-profit open-source platforms such as Mattermost. I remember being it fairly easy when the brainhack community migrated to Mattermost from Slack as they are very similar in use. I am aware that we would need to host our own instance of course as Cass suggested.

**Comment by cassgvp** [comment]
Closing this issue as the feedback from the soft launch was positive. May consider move away from slack if a WIN-wide alternative becomes available.
