### ISSUE TITLE
Community Participation Guidelines (Code of Conduct)

### ISSUE THREAD

**Issue by cassgvp** [cassgvp/WIN-Open-Neuroimaging-Community#5]
Please review the community [participation guidelines](https://cassgvp.github.io/WIN-Open-Neuroimaging-Community/docs/community/CODE_OF_CONDUCT.html)

- [x] What is the impression you gain about the community from this page?
- [x] Is this document important to you?
- [x] Do you have any feedback or suggestions as to how it would be improved?

**Comment by cassgvp** [comment]
Comment from Verena Heise:

- looks great to me, no comments

**Comment by TulikaN** [comment]
The instructions and guidelines are done very well. I really like the friendly tone and also that the instructions are brief and to the point :)

**Comment by mchiew** [comment]
This page looks great - I think you've made it very clear that this community will be inclusive and welcoming, and will not tolerate anti-social behaviour. I think it's an important document to have, and this is really well executed.
One thing that's come up in the Mosaic-related discussions is that we (as communities within the WIN) don't have much actual power to enforce codes of conduct, so we've been shifting towards framing things as "behavioural expectations" rather than "rules". I think you've done a great job here in directing people towards the University harassment policy and it's reporting guidelines. The WIN also will have Harassment Advisors that you could direct people towards (although I'm not sure when that list of individuals will be formalised yet). 

One other minor thing is that it would be great if there was a clickable link to edu.web.ox.ac.uk/harassment-advice somewhere on the page, as it's in the bottom of the info-graphic but not clickable.

**Comment by cassgvp** [comment]
Thanks @mchiew. 

> The WIN also will have Harassment Advisors that you could direct people towards (although I'm not sure when that list of individuals will be formalised yet).

This will be a great addition. Will look to include when the list has been formalised. 

> One other minor thing is that it would be great if there was a clickable link to edu.web.ox.ac.uk/harassment-advice somewhere on the page, as it's in the bottom of the info-graphic but not clickable.

Thank you for this suggestion. I've added a link in 078b56a8087553c5952aed36f52e488f3a04005c.

**Comment by JasleenKJolly** [comment]
Hi Cass, this is great and welcoming. I would love to see something around expanding awareness about how some people have difficulties and as a community we can help each other. For example, people with reading issues or dyslexia may struggle with spelling. There is a tone of acceptance and respect which is great.

**Comment by cassgvp** [comment]
Love this addition, @JasleenKJolly. I'm going to add it as an action below :).

- [x] Add a note to the participation guidelines about "how some people have difficulties and as a community we can help each other. For example, people with reading issues or dyslexia may struggle with spelling" and we can support each other by offering to proof and correct mistakes without judgement.

**Comment by cassgvp** [comment]
I've added a small section on "using your privilege" to cover the above in commit 3d982ed2b99b9bcf70fd2f70097eccb8f292b709 (see also 9c7fa9f2d46e073cd3f1d170b3cd3fa25f5ae128). This felt more appropriate than a specific reference to dyslexia, for example.
